FROM apache/kafka:4.2.0

# KRaft config
ENV KAFKA_NODE_ID=1
ENV KAFKA_PROCESS_ROLES=broker,controller
ENV KAFKA_CONTROLLER_QUORUM_VOTERS=1@localhost:9093

# Listeners
ENV KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
ENV KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
ENV KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
ENV KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
ENV KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT

# Single-node defaults
ENV KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
ENV KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
ENV KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1

# ---- Low resource tuning ----
# Cap JVM heap to 256mb (default is 1GB+)
ENV KAFKA_HEAP_OPTS="-Xms256m -Xmx256m"
# Use G1GC — better for small heaps
ENV KAFKA_JVM_PERFORMANCE_OPTS="-XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:+ExplicitGCInvokesConcurrent"
# Reduce background threads
ENV KAFKA_NUM_NETWORK_THREADS=2
ENV KAFKA_NUM_IO_THREADS=4
ENV KAFKA_NUM_PARTITIONS=1
# Smaller log segments to reduce memory mapping
ENV KAFKA_LOG_SEGMENT_BYTES=268435456
# Aggressive log cleanup to save disk
ENV KAFKA_LOG_RETENTION_HOURS=24
ENV KAFKA_LOG_RETENTION_BYTES=268435456

EXPOSE 9092