FROM bitnami/kafka:3.7

ENV KAFKA_CFG_NODE_ID=1

# KRaft mode ON
ENV KAFKA_CFG_PROCESS_ROLES=broker,controller
ENV KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@localhost:9093

# listeners
ENV KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
ENV KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://0.0.0.0:9092

ENV KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
ENV KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
ENV KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT

# IMPORTANT: disable zookeeper requirement
ENV KAFKA_ENABLE_KRAFT=yes
ENV KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv

EXPOSE 9092 9093